#!/bin/sh

# cdab-client is part of the software suite used to run Test Scenarios 
# for bechmarking various Copernicus Data Provider targets.
# 
# Copyright (C) 2020 Terradue Ltd, www.terradue.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Exception
#
# If you modify this file, or any covered work, by linking or combining it
# with Terradue.OpenSearch.SciHub (or a modified version of that library),
# containing parts covered by the terms of CC BY-NC-ND 3.0, the licensors
# of this Program grant you additional permission to convey or distribute
# the resulting work.

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/cdab-client

if [[ $@ == *"TS1"* ]]; then
    newargs="$@"
    newargs=${newargs/-tn/-ts}
    newargs=${newargs/--target_name/-ts}
    newargs=${newargs/--target_credentials/-tc}
    newargs=${newargs/-tu/-te}
    newargs=${newargs/-tsn/-n}
    newargs=${newargs/--testsite_name/-n}
    newargs=${newargs/--load_factor/-lf}

    newargs=`echo ${newargs} | sed -e 's/\(-\w*\)\ /\1=/g'`

    exec /usr/bin/cdab-remote-client $newargs
fi

exec mono $MONO_OPTIONS /usr/lib/cdab-client/bin/cdab-testtools.exe "$@"
