def descriptor = readYaml file: 'build.yml'
def dockerNewVersion = descriptor.version
def mType=getTypeOfVersion(env.BRANCH_NAME)

pipeline {
  parameters{
    string(name: 'dockerhub', defaultValue: 'cdab-git.acsys.it:5000', description: 'Hostname of the docker hub where to push the container images' )
    string(name: 'nodelabel', defaultValue: 'cdab-dev-ts01', description: 'Label of the node where to build the docker image' )
  }
  agent { node { label "${nodelabel}" } }
  stages {
    stage('Docker Build') {
      steps {
        sh  "docker build --no-cache --rm -t ${dockerhub}/centos7-testsite:${mType}${dockerNewVersion} -f Dockerfile --build-arg CDAB_RELEASE=${dockerNewVersion} . "
      }
    }
    stage('Docker Push') {
      steps {
        sh "docker tag ${dockerhub}/centos7-testsite:${mType}${dockerNewVersion} ${dockerhub}/centos7-testsite:${mType}latest"
        sh "docker push ${dockerhub}/centos7-testsite:${mType}${dockerNewVersion}"
        sh "docker push ${dockerhub}/centos7-testsite:${mType}latest"
      }
    }
  }
}



